name: 'SizeUp Action'
description: 'Estimate how easy a pull request will be to review'
author: 'Lérè Williams'

inputs:
  token:
    description: 'GitHub API token with read permissions for pull requests in this repository.'
    required: true
  configuration-file:
    description: 'Optional path to a YAML configuration file. This will be forwarded to sizeup.'

outputs:
  score:
    description: 'The numeric score that the pull request received.'
  category:
    description: 'The descriptive score category that the pull request was assigned.'

runs:
  using: node20
  main: dist/index.js

branding:
  icon: 'git-pull-request'
  color: 'green'
